# Generated by Django 6.0.5 on 2026-05-16 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cin', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cin_format', message='Le numéro de CIN doit comporter exactement 12 chiffres.', regex='^\\d{12}$')], verbose_name='Numéro de CIN')),
                ('scan_recto', models.ImageField(upload_to='scans/recto/%Y/%m/', verbose_name='Scan Face Recto')),
                ('scan_verso', models.ImageField(upload_to='scans/verso/%Y/%m/', verbose_name='Scan Face Verso')),
                ('photo_identite', models.ImageField(upload_to='photos/identite/%Y/%m/', verbose_name="Portrait d'identité")),
                ('is_duplicata', models.BooleanField(default=False, verbose_name='Type Duplicata')),
                ('date_remplacement', models.DateField(blank=True, null=True, verbose_name='Date de remplacement')),
                ('lieu_remplacement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de remplacement')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom patronymique')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('signe_particulier', models.TextField(blank=True, null=True, verbose_name='Signes particuliers visibles')),
                ('domicile', models.CharField(max_length=255, verbose_name='Adresse de domicile')),
                ('arrondissement', models.CharField(max_length=100, verbose_name='Arrondissement')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession / État')),
                ('nom_pere', models.CharField(max_length=255, verbose_name='Identité du Père')),
                ('nom_mere', models.CharField(max_length=255, verbose_name='Identité de la Mère')),
                ('date_creation', models.DateField(verbose_name='Date de délivrance originelle')),
                ('lieu_creation', models.CharField(max_length=255, verbose_name='Lieu de délivrance')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé et Prêt pour impression'), ('A_MODIFIER', "À modifier par l'opérateur")], default='EN_ATTENTE', max_length=20, verbose_name='État du dossier')),
                ('motif_modification', models.TextField(blank=True, null=True, verbose_name='Notes de rejet / Instructions de modification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'CIN',
                'verbose_name_plural': 'CINs',
                'ordering': ['-created_at'],
            },
        ),
    ]
